In [1]:
#code a neuron
#code layer of neurons
#using numpy to simplify the coding

In [4]:
#neuron with 3 inputs
inputs = [1, 2, 3]
weights = [0.2, 0.8,-0.5]
bias = 2
output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)

2.3


In [10]:
#layer of neurons
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
      [0.5, -0.91, 0.26, -0.5],
      [-0.26, -0.27, 0.17, 0.87]]

bias = [2, 3, 0.5]

"""
outputs = []
current_neuron = 1
for w in weights:
    for i in range(len(inputs)):
        op = w[i]*inputs[i]
    outputs.append(op + bias[current_neuron - 1])
    current_neuron += 1
print(outputs)
"""

#using zip()
neuron_output = []
for neuron_weights, neuron_bias in zip(weights, bias):
    op = 0
    for ip, weight in zip(inputs, neuron_weights):
        op = ip * weight
    op += neuron_bias
    neuron_output.append(op)
print(neuron_output)

[4.5, 1.75, 2.675]
[4.5, 1.75, 2.675]


In [12]:
#using numpy
import numpy as np
#single neuron
inputs = [1, 2, 3]
weights = [0.2, 0.5, 0.8]
bias = 0.45
output = np.dot(inputs, weights) + bias
print(output)

4.05


In [21]:
#using numpy
#layer
inputs = [0.1, 0.2, 0.3, 0.4]
weights = [[0.01, 0.02, 0.5, 0.8],
           [0.2, 0.04, 0.1, 0.09],
           [0.1, 0.001, 0.3, 0.4]]
bias = np.array([0.45, 0.67, 0.89])
output = np.dot(weights, inputs) + bias
print(output)
print("\n")

#batch
inputs = [[0.1, 0.2, 0.3, 0.4],
          [0.2, 0.3, 0.2, 0.5],
          [0.2, 0.4, 0.4, 0.6]]
weights = np.array([[0.01, 0.02, 0.5, 0.8],
           [0.2, 0.04, 0.1, 0.09],
           [0.1, 0.001, 0.3, 0.4]])
bias = np.array([0.45, 0.67, 0.89])
output = np.dot(inputs, np.transpose(weights)) + bias
print(output)

[0.925  0.764  1.1502]


[[0.925  0.764  1.1502]
 [0.958  0.787  1.1703]
 [1.14   0.82   1.2704]]
